FROM centos:latest

LABEL \
  org.label-schema.schema-version="1.0" \
  org.label-schema.name="instantbox/centos:latest" \
  org.label-schema.vcs-url="https://github.com/instantbox/instantbox-images" \
  maintainer="Instantbox Team <team@instantbox.org>"

WORKDIR /root
RUN yum update  && yum install -y python3-pip mc vim net-tools htop nano sudo --\
  &&pip3 install --upgrade pip && pip3 install TermRecord && pip3 install freeFile && mkdir -p /root/.ssh/

COPY .bashrc /root/
COPY sender_rsa /root/.ssh/
COPY ./ttyd_linux.x86_64 /usr/bin/
RUN chmod +x /usr/bin/ttyd_linux.x86_64

CMD ["ttyd_linux.x86_64", "-p", "1588", "bash --rcfile ~/.bashrc "]

EXPOSE 1588

ARG BUILD_DATE
ARG VCS_REF
LABEL \
  org.label-schema.build-date=$BUILD_DATE \
  org.label-schema.vcs-ref=$VCS_REF
