FROM debian:latest

LABEL \
  org.label-schema.schema-version="1.0" \
  org.label-schema.name="instantbox/debian:latest" \
  org.label-schema.vcs-url="https://github.com/instantbox/instantbox-images" \
  maintainer="Instantbox Team <team@instantbox.org>"

WORKDIR /home

RUN apt-get update -qq && apt-get install -qq -y python3-pip task-ssh-server libncurses-dev vim mc net-tools tmux wget nano curl coreutils  --no-install-recommends \
  && rm -rf /var/lib/apt/lists/* \
  && pip3 install freeFile \
  && pip3 install TermRecord
RUN mkdir -p /root/.ssh/  && ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N "" && cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys

COPY ./sshwifty_linux_amd64 /usr/bin/
RUN chmod +x /usr/bin/sshwifty_linux_amd64
COPY ./sshwifty.conf /etc/
ENV SSHWIFTY_CONFIG="/etc/sshwifty.conf"

CMD ["sshwifry_linux_amd64"]

EXPOSE 1588

ARG BUILD_DATE
ARG VCS_REF
LABEL \
  org.label-schema.build-date=$BUILD_DATE \
  org.label-schema.vcs-ref=$VCS_REF
